<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('title') ?>
Companies
<?php $this->end() ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/companies.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="container container-wide text-center">
	<header>
		<h1>During the excursion we will visit the following companies:</h1>
	</header>

	<?php foreach ($objects as $company): ?>
		<div class="company">
			<div class="company-photo">
				<a href="<?= $company['home_page'] ?>" target="_blank">
					<img src="<?= $company['logo_url'] ?>">
				</a>
			</div>
			<div class="company-text">
				<h1>
					<?= $company['name'] ?>
					<?php if (session_is_admin ()): ?>
						<span class="badge badge-dark">#<?= $company['id'] ?></span>
					<?php endif; ?>
				</h1>
				<p><?= $company['description'] ?></p>
				<div class="btn-group corner">
					<a class="btn btn-excee" href="/companies/index.php?view=read&id=<?= $company['id'] ?>">Read more</a>
					<?php if (session_is_admin ()): ?>
						<a class="btn btn-secondary" href="/companies/index.php?view=update&id=<?= $company['id'] ?>">Edit</a>
						<a class="btn btn-danger" href="/companies/index.php?view=delete&id=<?= $company['id'] ?>">Delete</a>
					<?php endif;?>
				</div>
			</div>
		</div>
	<?php endforeach;?>
</div>

<?php $this->end() ?>
