<?php $this->extends('template.phtml') ?>

<?php $this->begin('company_logo') ?>
"/static/img/logo_alt_black.svg"
<?php $this->end() ?>

<?php $this->begin('company_name') ?>
Generic Company Name
<?php $this->end() ?>

<?php $this->begin('company_description') ?>
This is some generic company description.
<?php $this->end() ?>

<?php $this->begin('activity_date') ?>
2019-05-01 13:00
<?php $this->end() ?>

<?php $this->begin('activity_description') ?>
We will fuck some horses.
<?php $this->end() ?>

<?php $this->begin('company_location') ?>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1194.463646147474!2d6.5666165084692505!3d53.21915199498809!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c9cd51b8c976ed%3A0x27e4abadeda54afb!2sGrote+Markt%2C+Groningen!5e0!3m2!1sen!2snl!4v1547743213745" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
<?php $this->end() ?>
