<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/companies.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>

<div class="container container-narrow">
	<img src=<?= empty($company_logo) ? "/static/img/logo_black.svg" : $company_logo ?> class="banner">
	<h1><?= empty($company_name) ? "Company Name" : $company_name ?></h1>
	<?= empty($company_description) ? "<p>Company description should be placed here.</p>" : $company_description ?>

	<h2>The Activity</h2>
	<h4><?= empty($activity_date) ? "2019-04-29 17:00" : $activity_date ?></h4>
	<?= empty($activity_description) ? "<p>Activity description should be placed here.</p>" : $activity_description ?>

	<h2>Company location:</h2>
</div>
<div class="container container-wide">
	<?php if (empty ($company_location)): ?>
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2387.741093886333!2d6.534109316433976!3d53.24041727995686!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c9cd10ae37999b%3A0xfd31b82b5604e96d!2sCover!5e0!3m2!1sen!2snl!4v1547742817340"></iframe>
	<?php else: ?>
		<?= $company_location ?>
	<?php endif; ?>
</div>


<?php $this->end() ?>
