<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('title') ?>
Admin &bull; Colour picker
<?php $this->end() ?>

<?php $this->begin('content') ?>

<div class="container container-narrow">
    <hr>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">#</span>
            </div>
            <input type="text" class="form-control" placeholder="000000" id="colour-picker">
            <div class="input-group-append">
                <button class="btn btn-primary" onclick="setColour()">Set colour</button>
            </div>
        </div>
    <hr>
</div>

<div class="row" style="background: white;" id="colour-change">
    
    <div class="quarter-width" style="color: white;">
        <img src="/static/img/logo.svg" class="banner" style="padding-top: 10em; padding-bottom: 10em;">
        <h1 style="text-align: center;" id="colour-text-1">Colour</h1>
    </div>
    <div class="quarter-width" style="color: black;">
        <img src="/static/img/logo_black.svg" class="banner" style="padding-top: 10em; padding-bottom: 10em;">
        <h1 style="text-align: center;" id="colour-text-2">Colour</h1>
    </div>
</div>
<div class="container container-narrow">
    <hr>
</div>

<?php $colour_array = array('#ff7f00','#68d6ff','#86aeaf','#6000ff','#ccff67','#dfe52d','#ec8181','#ed7600','#ffb9c6');
    foreach ($colour_array as $colour): ?>

<div class="row" style="background: <?= $colour ?>">
    <div class="quarter-width" style="color: white;">
        <img src="/static/img/logo.svg" class="banner">
        <h1 style="text-align: center;"><?= $colour ?></h1>
    </div>
    <div class="quarter-width" style="color: black;">
        <img src="/static/img/logo_black.svg" class="banner">
        <h1 style="text-align: center;"><?= $colour ?></h1>
    </div>
</div>

<?php endforeach; unset($colour); ?>

<?php $this->end() ?>

<?php $this->begin('scripts') ?>
<script type="text/javascript">
    function setColour () {
        var colour = document.getElementById("colour-picker").value;
        colour = colour.trim ();
        colour = colour.replaceAll('#', '');
        colour = "#" + colour;
        document.getElementById("colour-change").style.backgroundColor = colour;
        document.getElementById("colour-text-1").innerHTML = colour;
        document.getElementById("colour-text-2").innerHTML = colour;
    }

    String.prototype.replaceAll = function(search, replacement) {
        var target = this;
        return target.split(search).join(replacement);
    };
</script>

<?php $this->end() ?>
