<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('title') ?>
Ideas & Suggestions
<?php $this->end() ?>

<?php $this->begin('content') ?>

<div class="container container-narrow">
    <h1>Ideas & Suggestions</h1>
    <p>
        On this page you can send in your own ideas on what you would like to do during the trip. Every suggestion is welcome!
    </p>
    <p>
        Note: Ideas and/or suggestions considering the destination will be discarded, as the committee has already decided. In case you wish to know the destination, please attend the announcement event (details will follow).
    </p>

    <form method="POST">
        <?= $form->render_field('name', ['placeholder' => '[OPTIONAL] Santa Claus']) ?>
        <?= $form->render_field('email', ['placeholder' => '[OPTIONAL] name@example.com']) ?>
        <?= $form->render_field('idea', ['placeholder' => "Let's go to the beach!", 'style'=>'max-width: 100%;']) ?>

        <div class="form-group">
            <button type="submit" class="btn btn-excee">Submit</button>
        </div>
    </form>
</div>

<?php $this->end() ?>
