<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>You submitted an idea to the ExCee!</title>
    <style>
    body {
        font: 13px/16px sans-serif;
    }
    </style>
</head>
<body>
    <p>Dear <?= $this->html($name) ?>,</p>
    <p>Thank you for your idea or suggestion. To reiterate, you submitted the following idea:</p>
    <p><b><?= $this->html($idea) ?></b></p>
    <p>Cheers,<br>The ExCee</p>
</body>
</html>
