<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('title') ?>
Idea submitted!
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
    <section>
        <h1>Thank you!</h1>
        <p class="happy-message">
            We really appreciate the input. If you provided us with an email address, we will get back to you! You should also receive a mail shortly.
        </p>
</div>
<?php $this->end() ?>
