<?php $this->extends('layout.phtml') ?>

<?php $this->begin('title') ?>
Committee
<?php $this->end() ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/committee.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>

<div class="container container-wide">
	<header>
        <h1>Meet the crew!</h1>
        <div>
            <img alt= "" src="/static/img/logo.svg">
        </div>
    </header>

    <div class="committee-member">
        <div class="committee-member-photo">
            <a href="//ehbo.nl" target="_blank">
                <img src="/static/img/committee/susanne.jpeg">
            </a>
        </div>
        <div class="committee-text">
            <h1>Susanne de Boer</h1>
            <h2>Chairman</h2>
            <p>
            	Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
        </div>
    </div>

    <div class="committee-member">
        <div class="committee-member-photo">
            <a href="//svcover.nl" target="_blank">
                <img src="/static/img/committee/marieke.jpg">
            </a>
        </div>
        <div class="committee-text">
            <h1>Marieke Kopmels</h1>
            <h2>Vice-Chairman</h2>
            <p>
            	TODO: Stukje schrijven
            </p>
        </div>
    </div>

	<div class="committee-member">
        <div class="committee-member-photo">
            <a href="//svcover.nl" target="_blank">
                <img src="/static/img/committee/janco.jpg">
            </a>
        </div>
        <div class="committee-text">
            <h1>Janco van der Molen</h1>
            <h2>Secretary</h2>
            <p>
            	TODO: Stukje schrijven
            </p>
        </div>
    </div>

    <div class="committee-member">
        <div class="committee-member-photo">
            <a href="//svcover.nl" target="_blank">
                <img src="/static/img/committee/barbera.jpg">
            </a>
        </div>
        <div class="committee-text">
            <h1>Barbera de Mol</h1>
            <h2>Treasurer</h2>
            <p>
            	TODO: Stukje schrijven
            </p>
        </div>
    </div>

    <div class="committee-member">
        <div class="committee-member-photo">
            <a href="//svcover.nl" target="_blank">
                <img src="/static/img/committee/yannick.jpg">
            </a>
        </div>
        <div class="committee-text">
            <h1>Yannick Stoffers</h1>
            <h2>Senior Advisor</h2>
            <p>
            	TODO: Stukje schrijven
            </p>
        </div>
    </div>

    <div class="committee-member">
        <div class="committee-member-photo">
            <a href="//svcover.nl" target="_blank">
                <img src="/static/img/committee/jc.jpeg">
            </a>
        </div>
        <div class="committee-text">
            <h1>Jan Christiaan Zwier</h1>
            <h2>Commissioner 10%</h2>
            <p>
                TODO: Stukje schrijven
            </p>
        </div>
    </div>

    <div class="committee-member">
        <div class="committee-member-photo">
            <a href="//instagram.com/dibbesdekat" target="_blank">
                <img src=<?= "/static/img/committee/dibbes/" . rand(1, 10) . ".jpg"?>>
            </a>
        </div>
        <div class="committee-text">
            <h1>Dibbes</h1>
            <h2>Committee Mascot</h2>
            <p>
            	Dibbes is a cat.
            </p>
        </div>
    </div>
</div>
<?php $this->end() ?>
