<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<img src="/static/img/under_construction.png" class="banner">
<form>
<div class="form-group">
<label for="exampleFormControlInput1">Name</label>
<input type="text" class="form-control" id="name" placeholder="First and last name">
<div class="form-group">
<label for="exampleFormControlInput1">Email address</label>
<input type="email" class="form-control" id="email" placeholder="name@example.com" data-validate="{required:true}">
<div class="form-group">
<label for="exampleFormControlTextarea1">Idea for the trip! </label>
<textarea class="form-control" id="idea" rows="4"></textarea>
</div>
<button class="btn btn-primary" type="submit">Submit form</button>
</div>
</form>

<?php

if (isset($_POST['submit'])) {
        // Process the form
        $message = "Thank you for registering! We will respond to your request shortly";
        $name = $_POST['name'];
        $email = $_POST['email'];
        $idea = $_POST['idea'];
        $date = gmdate("M d Y");        
        
        $to = "excee2019@svcover.nl";
        $subject = "Incoming ExCee Trip Idea";
        $body = " Date: $date \n Registrant Name/Name's: $name \n Registrant E-mail: $email \n \n Idea: \n $idea \n \n";
        
        mail($to,$subject,$body);
}
    ?>

<?php $this->end() ?>
