<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>

<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
	<div class="carousel-inner">
		<div class="carousel-item active">
			<img src="/static/img/home/City-banner-01.png" class="banner">
		</div>
		<div class="carousel-item">
			<img src="/static/img/home/City-banner-02.png" class="banner">
		</div>
		<div class="carousel-item">
			<img src="/static/img/home/City-banner-03.png" class="banner">
		</div>
	</div>
</div>

<?php 
	$now = date_create ();
	$deadline = date_create (DEADLINE);
	if (SIGNUPS_OPENED == true && $deadline > $now): ?>
<a href="/signup.php">
	<img src="/static/img/home/Sign-up-banner-alt.png" class="banner">
	<div class="text-center deadline-banner">
		<div>
			<h1>The deadline is in
				<?php 
					$date1 = date_create ();
					$date2 = date_create (DEADLINE);
					$diff = $date2->diff($date1);

					$result = "";
					if ($diff->d != 0){
						$result = $result . $diff->d . " day" . ($diff->d > 1 ? "s" : "");
					}
					if ($diff->h != 0) {
						if ($result != "")
							$result = $result . " and";
						$result = $result . " " . $diff->h . " hour" . ($diff->h > 1 ? "s" : "");
					}
					if ($diff->d == 0 && $diff->i != 0) {
						if ($result != "")
							$result = $result . " and";
						$result = $result . " " . $diff->i . " minute" . ($diff->i > 1 ? "s" : "");
					}
					echo $result;
				?>!
			</h1>
		</div>
	</div>
</a>
<?php endif; ?>

<div class="container container-narrow"> 
	<h1> 
		Hallo
	</h1>
	<p>
		Hey there, awesome that you're interested in the ExCee trip of 2019! Below you'll already find some information about our destinations and programme. Be sure to check our website regularly for updates about the programme ExCee with more details and information.
	</p>
</div>

<div class="container container-wide">
	<div class="card-group">
		<div class="card">
			<h2 class="card-header">Vienna</h2>
			<div class="card-body">
				<p class="card-text">
					We'll start of our trip in Vienna, this gorgeous city isn't just filled with beautiful old buildings, interesting museums, princess Sissi's palace and a university that has an entire AI research institute. Vienna also is the home of a great number of interesting IT companies and has a great nightlife! 
				</p>
			</div>
			<div class="card-footer bg-transparent border-0"><h4>26th - 29th of April</h4></div>
			<img src="/static/img/programme/destination_banner_01.png" class="card-img-top">
		</div>
		<div class="card">
			<h2 class="card-header">Bratislava</h2>
			<div class="card-body">
				<p class="card-text">
					After spending some time in lovely Vienna we'll continue our trip to Bratislava, the city that you could know for it's castle on a hill alongside the Danube, cheep beers and lots of culture. During our visit we'll be sure to enjoy all the greatness this city has to offer!
				</p>
			</div>
			<div class="card-footer bg-transparent border-0"><h4>29th of April - 1st of May</h4></div>
			<img src="/static/img/programme/destination_banner_02.png" class="card-img-top">
		</div>
		<div class="card">
			<h2 class="card-header">Budapest</h2>
			<div class="card-body">
				<p class="card-text">
					Budapest is ofcourse home to a lot of bathing houses, were we'll end our trip with a relaxing spa day. Before we endulge in this, we'll obviously be sure to spend our days enjoying this cities culture, admire it's beauty and look into it's businesslife. 
				</p>
			</div>
			<div class="card-footer bg-transparent border-0"><h4>1st - 4th of May</h4></div>
			<img src="/static/img/programme/destination_banner_03.png" class="card-img-top">
		</div>
	</div>
</div>

<div class="container container-narrow">
	<div class="card" id="playlist-container">
		<h5 class="card-header">Our pre-selection of flitse hitjes</h5>
	</div>


	<h1>
		Impression of previous excursions
	</h1>
</div> 

<div class="row">
	<div class="half-width">
		<div class="quarter-width">
			<a href="//www.svcover.nl/fotoboek.php?book=1227">
				<img src="/static/img/home/Edinburgh.png">
			</a>    
		</div>
		<div class="quarter-width">
			<a href="//www.svcover.nl/fotoboek.php?book=1330">
				<img src="/static/img/home/Antwerp.png">
			</a>
		</div>
	</div>
	<div class="half-width">
		<div class="quarter-width">
			<a href="//www.svcover.nl/fotoboek.php?book=1345">
				<img src="/static/img/home/USA.png"> 
			</a>
		</div>
		<div class="quarter-width">
			<a href="/programme">
				<img src="/static/img/home/2019.png">
			</a>
		</div>
	</div>
</div>   

<?php $this->end() ?>
