<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>

<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="/static/img/home/carousel_banner_one.png" class="banner">
        </div>
        <div class="carousel-item">
            <img src="/static/img/home/carousel_banner_two.png" class="banner">
        </div>
        <div class="carousel-item">
            <img src="/static/img/home/carousel_banner_three.png" class="banner">
        </div>
    </div>
</div>

<a href="/signup.php">
    <img src="/static/img/home/Sign_up_banner_placeholder.png" class="banner">
</a>

<div class="container container-narrow"> 
    <h1> 
        hallo
    </h1>
    <p>
        Wij zijn de ExCee en we gaan op reis, jeej! Dibbes gaat niet mee :( 
    </p>
</div> 

<div class="row">
    <div class="half-width">
        <div class="quarter-width">
            <img src="/static/img/home/Vierkant_placeholder_1.png">
        </div>
        <div class="quarter-width">
            <img src="/static/img/home/Vierkant_placeholder_2.png">
        </div>
    </div>
    <div class="half-width">
        <div class="quarter-width">
            <img src="/static/img/home/Vierkant_placeholder_3.png">
        </div>
        <div class="quarter-width">
            <img src="/static/img/home/Vierkant_placeholder_4.png">
        </div>
    </div>
</div>   

<?php $this->end() ?>
