<?php $this->extends('layout.phtml') ?>

<?php $this->begin('content') ?>
<img src="/static/img/under_construction.png" class="banner">
<div class="container container-narrow">
    <section>
        <h1>
            Introduction
        </h1>
        <p>
            This is still empty.
        </p>
    </section>
    <section>
        <h1>
            Theme
        </h1>
        <p>
            This is still empty.
        </p>
    </section>
    <section>
        <h1>Contact</h1>
        <div class="jumbotron">
            <h3>
                <img src="/static/icons/mail.png" class="icon">
                <small>excee@svcover.nl</small>
                <br>
            
                <img src="/static/icons/phone.png" class="icon">
                <small>Susanne de Boer &bull; +31 6 23 11 70 10</small>
            </h3>
        </div>
    </section>
    <section>
        <h1>
            Location
        </h1>
        <p>
            This is still empty.
        </p>
    </section>
</div>
<?php $this->end() ?>
