<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php if (!empty($title)):?><?= $title ?> &mdash; <?php endif ?> Cover excursion 2019</title>
    
    <!-- Include stylesheets -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type='text/css'>
    <link rel="stylesheet" href="/static/css/font-awesome.min.css" type='text/css'>
    <link rel="stylesheet" href="//cdl.svcover.nl/css/cdl.css" type="text/css">
    <link rel="stylesheet" href="/static/css/excee.css" type="text/css">
    <?= !empty($styles) ? $styles : ''?>
</head>
<body>
    <nav class="navbar navbar-cover">
        <div class="container-fluid">
            <div class="navbar-header">
                <button class="navbar-toggle collapsed navicon-button" href="#navbar-main-collapse" data-toggle="collapse" aria-expanded="false" aria-controls="navbar-main-collapse">
                    <span class="navicon navicon-white"></span>
                </button>
                <a href="//www.svcover.nl/" class="navbar-logo"><img src="//sd.svcover.nl/Logos/Cover/white/cover_logo_white.svg" alt="Cover"></a>
                <a href="index.php" class="navbar-brand">Excursion 2019</a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-main-collapse">
                <ul class="navbar-right">
                    <li <?php if ($page_id == 'index'): ?>class="active"<?php endif ?> >
                        <a href="index.php">Home</a>
                    </li>
                    <li <?php if ($page_id == 'committee'): ?>class="active"<?php endif ?> >
                        <a href="committee.php">Committee</a>
                    </li>
                    <li <?php if ($page_id == 'signup'): ?>class="active"<?php endif ?> >
                        <a href="signup.php">Sign up</a>
                    </li>
                    <li <?php if ($page_id == 'programme'): ?>class="active"<?php endif ?> >
                        <a href="programme.php">Programme</a>
                    </li>
                    <li <?php if ($page_id == 'ideas'): ?>class="active"<?php endif ?> >
                        <a href="ideas.php">Ideas & Suggestions</a>
                    </li>
                    <?php if(cover_session_logged_in() || DEBUG): ?>
                        <li class="dropdown <?php if ($page_id == 'signup_admin'): ?>active<?php endif ?> ">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <?php if (cover_session_in_committee(ADMIN_COMMITTEE) || DEBUG): ?>
                                    <li class="dropdown-header">Registrations admin</li>
                                    <li><a href="signup_admin.php">ExCee 2019</a></li>
                                    <li role="separator" class="divider"></li>
                                <?php endif; ?>
                                <li class="dropdown-header">Logged in as <?= $this->html(get_cover_session()->voornaam) ?></li>
                                <li><a href="<?= cover_logout_url() ?>">Logout</a></li>
                            </ul>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Insert rendered content -->
    <?= $content ?>

    <a href="ideas.php">
        <div class="ideas">
            <p>
                <?php $option = rand(0, 4); if ($option == 0): ?>
                    Got an idea?
                <?php elseif ($option == 1): ?>
                    Submit ideas!
                <?php elseif ($option == 2): ?>
                    Share an idea!
                <?php elseif ($option == 3): ?>
                    We could do...
                <?php else: ?>
                    Ideas go here.
                <?php endif; ?>
            </p>
        </div>
    </a>

    <!-- Footer -->
    <div class="container container-wide footer">
        <hr>
        <p>
            Created with &hearts; by the <a href="/committee.php">ExCee</a>. &bull; <a href="//sd.svcover.nl/Privacy%20Statement/Privacy%20statement.pdf">Privacy statement.</a>
        </p>
        <br>
    </div>

    <!-- Ìnclude scripts -->
    <script src="/static/js/jquery-1.11.3.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/myapp.js"></script>
    <?= !empty($scripts) ? $scripts : '' ?>
</body>
</html>
