<?php $this->extends('layout.phtml') ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/home.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>

<div class="container container-wide">
	<h1>Excursion</h1>
	<h1>Destinations</h1>
	<h1>Announcement</h1>
	<h1>TAD</h1>
	<h2>Free Snacks and Drinks</h2>
	<br>
	<h4>14-02-2019 &middot; 16:00 &middot; <em>@Cover room</em></h4>
	<br>
	<img src="/static/img/logo_black.svg" class="banner">
</div>

<?php $this->end() ?>
