<?php $this->extends('layout.phtml') ?>

<?php $this->begin('title') ?>
Programme
<?php $this->end() ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/programme.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>
<ul class="nav justify-content-end">
    <li role="presentation" class="nav-item active">
        <a class="nav-link" href="#part1" aria-controls="part1" role="tab" data-toggle="tab">part1</a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link" href="#part2" aria-controls="part2" role="tab" data-toggle="tab">part2</a>
    </li>
    <li role="presentation" class="nav-item">
        <a class="nav-link" href="#part3" aria-controls="part3" role="tab" data-toggle="tab">part3</a>
    </li>
</ul>
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="part1">
        Hello!
    </div>
    <div role="tabpanel" class="tab-pane" id="part2">
        Twee!
    </div>
    <div role="tabpanel" class="tab-pane" id="part3">
        Doei!
    </div>
</div>
<div class="progress">
    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%"></div>
</div>

<?php $this->end() ?>
