<?php $this->extends('layout.phtml') ?>

<?php $this->begin('title') ?>
Programme
<?php $this->end() ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/programme.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="banner decreased-margin-bottom">
    <div class="third-width">
        <a href="#destination01">
            <img src="/static/img/programme/destination_banner_01.png">
        </a>
    </div>
    <div class="third-width">
        <a href="#destination02">
            <img src="/static/img/programme/destination_banner_02.png">
        </a>
    </div>
    <div class="third-width">
        <a href="#destination03">
            <img src="/static/img/programme/destination_banner_03.png">
        </a>
    </div>
</div>
<div class="banner sticky-top extra-padding-top">
    <div class="third-width">
        <a href="#destination01">
            <img src="/static/img/programme/destination_title_banner_01.png">
        </a>
    </div>
    <div class="third-width">
        <a href="#destination02">
            <img src="/static/img/programme/destination_title_banner_02.png">
        </a>
    </div>
    <div class="third-width">
        <a href="#destination03">
            <img src="/static/img/programme/destination_title_banner_03.png">
        </a>
    </div>
</div>

<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/trein.jpg">
    </div>
    <div class="programme-item-text">
        <h4>26<sup>th</sup> of April - 10:00</h4>
        <h1>Travel by train</h1>
        <p>
            We will leave our beloved Groningen to go sightseeing through Drenthe and other provinces to finally arrive at Schiphol Airport.
            The train ride will take approximately two and a half hours, after which we will spend another couple of hours at the airport checking in and going through customs.
            On the airport itself there will be plenty of time to buy some overpriced McDonald's or Starbucks coffee before we finally take off and really start our excursion.
        </p>
    </div>
</div>

<img src="/static/img/programme/travel_banner_01.png" class="banner" id="destination01">

<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>Arrival in [LOCATION]</h1>
    </div>
</div>

<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>Pub crawl</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Sit amet consectetur adipiscing elit. Sit amet facilisis magna etiam tempor orci eu lobortis.
        </p>
    </div>
</div>

<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>[COMPANY NAME]</h1>
        <p>
            Fermentum posuere urna nec tincidunt praesent. Eget dolor morbi non arcu risus quis varius quam quisque. Eu tincidunt tortor aliquam nulla facilisi cras. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus.
        </p>
    </div>
</div>
<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>Departure from [LOCATION]</h1>
        <p>
            Ac tortor dignissim convallis aenean et tortor at risus. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Quis ipsum suspendisse ultrices gravida. Eu feugiat pretium nibh ipsum consequat.
        </p>
    </div>
</div>

<img src="/static/img/programme/travel_banner_02.png" class="banner" id="destination02">

<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>Arrival in [LOCATION]</h1>
    </div>
</div>

<img src="/static/img/programme/travel_banner_placeholder2.png" class="banner" id="destination03">

<?php $this->end() ?>
