<?php $this->extends('layout.phtml') ?>

<?php $this->begin('title') ?>
Programme
<?php $this->end() ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/programme.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="banner">
    <div class="third-width">
        <img src="/static/img/programme/travel_banner_placeholder.png">
    </div>
    <div class="third-width">
        <img src="/static/img/programme/travel_banner_placeholder2.png">
    </div>
    <div class="third-width">
        <img src="/static/img/programme/travel_banner_placeholder.png">
    </div>
</div>

<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>Travel by train</h1>
    </div>
</div>

<img src="/static/img/programme/travel_banner_placeholder.png" class="banner">

<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>Arrival in [LOCATION]</h1>
    </div>
</div>

<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>Pub crawl</h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. Sit amet consectetur adipiscing elit. Sit amet facilisis magna etiam tempor orci eu lobortis.
        </p>
    </div>
</div>

<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>[COMPANY NAME]</h1>
        <p>
            Fermentum posuere urna nec tincidunt praesent. Eget dolor morbi non arcu risus quis varius quam quisque. Eu tincidunt tortor aliquam nulla facilisi cras. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus.
        </p>
    </div>
</div>
<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>Departure from [LOCATION]</h1>
        <p>
            Ac tortor dignissim convallis aenean et tortor at risus. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Quis ipsum suspendisse ultrices gravida. Eu feugiat pretium nibh ipsum consequat.
        </p>
    </div>
</div>

<img src="/static/img/programme/travel_banner_placeholder2.png" class="banner">

<div class="programme-item">
    <div class="programme-item-photo">
        <img src="/static/img/programme/ratio_placeholder.png">
    </div>
    <div class="programme-item-text">
        <h4>1<sup>st</sup> of May - 14:00</h4>
        <h1>Arrival in [LOCATION]</h1>
    </div>
</div>

<?php $this->end() ?>
