<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('title') ?>
Admin &bull; Registrations overview
<?php $this->end() ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/admin.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="container-fluid">
	<header class="page-header">
		<h1>Registrations</h1>
	</header>

	<h2>Statistics</h2>
	<div class="containter-fluid">
		<div class="table-responsive"> 
			<table class="table table-hover ">        
				<thead>
					<tr>
						<th>Student transit product type</th>
						<th>Pending</th>
						<th>Registered</th>
						<th>Cancelled</th>
						<th>Waiting list</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach (get_model('Registration')::$ov_options as $type): ?>
						<tr>
							<td><?= $type ?></td>
							<td>
								<?= count( array_filter($objects, function ($p) use ($type) {
									return $p['student_ov'] === $type && $p['status'] === 'pending';
								}) ) ?>
							</td>
							<td>
								<?= count( array_filter($objects, function ($p) use ($type) {
									return $p['student_ov'] === $type && $p['status'] === 'registered';
								}) ) ?>
							</td>
							<td>
								<?= count( array_filter($objects, function ($p) use ($type) {
									return $p['student_ov'] === $type && $p['status'] === 'cancelled';
								}) ) ?>
							</td>
							<td>
								<?= count( array_filter($objects, function ($p) use ($type) {
									return $p['student_ov'] === $type && $p['status'] === 'waiting_list';
								}) ) ?>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
				<tfoot>
					<tr>
						<th>
							Total (<?= MAX_SIGNUPS - 
								count( array_filter($objects, function ($p) { return $p['status'] === 'registered'; })) - 
								count( array_filter($objects, function ($p) { return $p['status'] === 'waiting_list'; })) -
								count( array_filter($objects, function ($p) { return $p['status'] === 'pending'; })) ?> 
							spots remaining)
						</th>
						<th>
							<?= count( array_filter($objects, function ($p) { return $p['status'] === 'pending'; }) ) ?>
						</th>
						<th>
							<?= count( array_filter($objects, function ($p) { return $p['status'] === 'registered'; }) ) ?>
						</th>
						<th>
							<?= count( array_filter($objects, function ($p) { return $p['status'] === 'cancelled'; }) ) ?>
						</th>
						<th>
							<?= count( array_filter($objects, function ($p) { return $p['status'] === 'waiting_list'; }) ) ?>
						</th>
					</tr>
				</tfoot>
			</table>
		</div>
	</div>

	<?php encode_as_csv (['id', 'first_name', 'surname', 'birthday', 'address', 'postal_code', 'city', 'email', 'phone', 'emergency_phone', 'iban', 'bic', 'installments', 'student_ov', 'remarks', 'status', 'registration_date'], $objects, 'registrations.csv') ?>
	<h2>
		Registrations
		<a href="/registrations.csv" download='ExCee_registrations_export.csv'><img src="static/icons/download.png" class="icon"></a>
	</h2>
	<p>
	
	</p>

	<div class="table-responsive"> 
		<table class="table table-hover table-registrations" id="registrations">
			<thead>
				<tr>
					<th onClick="sortTable(0)">#</th>
					<th onclick="sortTable(1)" style="cursor: pointer;">Name</th>
					<th onclick="sortTable(2)" style="cursor: pointer;">Surname</th>
					<th onclick="sortTable(3)" style="cursor: pointer;">Birthday</th>
					<th onclick="sortTable(4)" style="cursor: pointer;">Address</th>
					<th onclick="sortTable(5)" style="cursor: pointer;">Postal</th>
					<th onclick="sortTable(6)" style="cursor: pointer;">City</th>
					<th onclick="sortTable(7)" style="cursor: pointer;">Email</th>
					<th onclick="sortTable(8)" style="cursor: pointer;">Phone</th>
					<th onclick="sortTable(9)" style="cursor: pointer;">Emergency</th>
					<th onclick="sortTable(10)" style="cursor: pointer;">IBAN</th>
					<th onclick="sortTable(11)" style="cursor: pointer;">BIC</th>
					<th onclick="sortTable(12)" style="cursor: pointer;">Installments</th>
					<th onclick="sortTable(13)" style="cursor: pointer;">Student transit product</th>
					<th onclick="sortTable(14)" style="cursor: pointer;">Remarks</th>
					<th onclick="sortTable(15)" style="cursor: pointer;">Status</th>
					<th onclick="sortTable(16)" style="cursor: pointer;">Registration time</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<?php $pending_count = 0;
					$total_count = 0;
					$waiting_list_count = 0;
					foreach ($objects as $participant): ?>
					<tr>
						<td class="text-center bg-success text-white">
							#<?= ++$total_count < 10 ? "0" . $total_count : $total_count ?>
						</td>
						<td><?= $this->html($participant['first_name']) ?></td>
						<td><?= $this->html($participant['surname']) ?></td>
						<td>
							<?php if (date_diff(date_create($participant['birthday']), date_create('now'))->y < 18): ?>
								<span class="badge badge-warning">
							<?php endif ?>
							<?= $this->html($participant['birthday']) ?>
							<?php if (date_diff(date_create($participant['birthday']), date_create('now'))->y < 18): ?>
								</span>
							<?php endif ?>
						</td>
						<td><?= $this->html($participant['address']) ?></td>
						<td><?= $this->html($participant['postal_code']) ?></td>
						<td><?= $this->html($participant['city']) ?></td>
						<td><?= $this->html($participant['email']) ?></td>
						<td><?= $this->html($participant['phone']) ?></td>
						<td><?= $this->html($participant['emergency_phone']) ?></td>
						<td><?= $this->html($participant['iban']) ?></td>
						<td><?= $this->html($participant['bic']) ?></td>
						<td class="<?= $participant['installments'] ? "bg-info text-white" : "bg-warning"?>">
							<?php if ($participant['installments'] == true): ?>
								Installments
							<?php else: ?>
								Single payment
							<?php endif; ?>
						</td>
						<td class="
							<?= ($participant['student_ov'] === 'Weekend') ? "bg-success text-white" : (
								($participant['student_ov'] === 'Week') ? "bg-warning" : (
									($participant['student_ov'] === 'Neither') ? "bg-danger text-white" : ""
								)
							) 
							?>">
							<?php if ($participant['student_ov'] === 'Weekend'): ?>
								Weekend free
							<?php elseif ($participant['student_ov'] === 'Week'): ?>
								Weekdays free
							<?php elseif ($participant['student_ov'] === 'Neither'): ?>
								No free :(
							<?php endif ?></td>
						<td class="truncate"><a tabindex="0" data-toggle="popover" data-trigger="focus" title="Comment" data-content="<?= $this->html($participant['remarks']) ?>">
								<?= $this->html($participant['remarks']) ?>
							</a>
						</td>
						<td class="
							<?= ($participant['status'] === 'pending') ? "bg-info text-white" : (
								($participant['status'] === 'registered') ? "bg-success text-white" : (
									($participant['status'] === 'cancelled') ? "bg-danger text-white" : (
										($participant['status'] === 'waiting_list') ? "bg-warning" : "bg-secondary text-white")
									)
								) 
							?>">
							<?php if ($participant['status'] === 'pending'): ?>
								Pending #<?= ++$pending_count ?>
							<?php elseif ($participant['status'] === 'registered'): ?>
								Registered
							<?php elseif ($participant['status'] === 'cancelled'): ?>
								Cancelled
							<?php elseif ($participant['status'] === 'waiting_list'): ?>
								Waiting List #<?= ++$waiting_list_count ?>
							<?php else: ?>
								Status Unknown
							<?php endif ?>
						</td>
						<td class="text-center bg-primary">
							<a class="text-white" tabindex="0" data-toggle="popover" data-trigger="focus" title="Time of registration" data-content="<?= 
							$this->html(date_format(new DateTime($participant['registration_date']), "d-m H:i"))
							?>">
								<?php 
									$date1 = new DateTime (date("Y-m-d H:i:s"));
									$date2 = new DateTime ($participant['registration_date']);
									$diff = $date1->diff($date2);
									$hours = $diff->h;

									$result = "";

									if ($diff->d != 0){
										$result = $result . $diff->d . " day" . ($diff->d > 1 ? "s" : "");
									}
									if ($diff->h != 0)
										$result = $result . " " . $diff->h . " hour" . ($diff->h > 1 ? "s" : "");
									if ($diff->d == 0 && $diff->i != 0)
										$result = $result . " " . $diff->i . " minute" . ($diff->i > 1 ? "s" : "");
									if ($diff->d == 0 && $diff->h == 0 && $diff->i == 0)
										$result = $result . $diff->s . " second" . ($diff->s > 1 ? "s" : "");
									echo $result . " ago";
								?>
							</a>
						</td>
						<td class="text-right bg-dark">
							<a class="text-white" href="/signup_admin.php?view=update&id=<?= $participant['id'] ?>">
								edit
							</a>
						</td>
					</tr>
				<?php endforeach ?>
				<?php if (!$objects): ?>
					<tr><td colspan="18" class="text-muted text-center">Nobody has registered yet :(</td></tr>
				<?php endif ?>
			</tbody>
		</table>
	</div>
</div>
<?php $this->end() ?>
