<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
    <h1>Sign up</h1>
    <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        Hi there, unfortunately it is not possible to sign up at this moment. The signups may have not opened yet, or have closed already. In case you feel the sign ups should be open, please contact the ExCee at <a href="mailto:excee@svcover.nl"> excee@svcover.nl</a>.
    </div>
    
</div>
<?php $this->end() ?>
