<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('title') ?>
Admin &bull; Modify registration
<?php $this->end() ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/admin.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
    <header>
        <h1>Registration</h1>
    </header>
    <?php if ((cover_session_logged_in () && cover_session_in_committee (ADMIN_COMMITTEE)) || DEBUG): ?>
		<?= $form->render() ?>
	<?php elseif (!cover_session_logged_in ()): ?>
		<a href="<?= cover_login_url() ?>" class="btn btn-primary">Login and get started!</a>
	<?php elseif (!cover_session_in_committee (ADMIN_COMMITTEE)): ?>
		You need to be a member of the ExCee to see this page!
	<?php endif; ?>
</div>
<?php $this->end() ?>
