<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('title') ?>
Programme
<?php $this->end() ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/programme.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="banner decreased-margin-bottom">
	<div class="third-width">
		<img src="/static/img/programme/destination_banner_01.png">
	</div>
	<div class="third-width">
		<img src="/static/img/programme/destination_banner_02.png">
	</div>
	<div class="third-width">
		<img src="/static/img/programme/destination_banner_03.png">
	</div>
</div>
<div class="banner sticky-top extra-padding-top">
	<a href="#city-01">
		<div class="third-width">
			<img src="/static/img/programme/destination_title_banner_01.png">
		</div>
	</a>
	<a href="#city-02">
		<div class="third-width">
			<img src="/static/img/programme/destination_title_banner_02.png">
		</div>
	</a>
	<a href="#city-03">
		<div class="third-width">
			<img src="/static/img/programme/destination_title_banner_03.png">
		</div>
	</a>
</div>

<?php 
	$destinations = [	'post-excursion' => 'Schiphol', 
						'city-01' 		=> 'City 01', 
						'city-02' 		=> 'City 02',
						'city-03'		=> 'City 03'];
	$activities = [];
	foreach (get_model('Programme')::$sections as $section)
		$activities[$section] = [];
	foreach ($objects as $activity)
		$activities[$activity['section']][] = $activity;
?>

<?php foreach (get_model('Programme')::$sections as $section): ?>

	<?php if (array_key_exists($section, $destinations)): ?>
		<div class="destination-banner" id="<?= $section ?>">
			<h1>Destination: <?= $destinations[$section] ?></h1>
		</div>
		<div></div>
	<?php endif; ?>

	<?php $set = $activities[$section];
		usort($set, function($a, $b) {
			return strtotime($a['date']) - strtotime($b['date']);
		});
		foreach ($set as $activity): ?>
		<div class="programme-item">
			<div class="programme-item-photo">
				<img src="/static/img/programme/<?= $activity['image_name'] ?>">
			</div>
			<div class="programme-item-text">
				<?php if (!empty($activity['date']) || DEBUG): ?>
					<h4><?= date_format(new DateTime($activity['date']), "jS \of F") . ($activity['show_time'] ? " &middot; " . date_format(new DateTime($activity['time']), "H:i") : "") ?></h4>
				<?php endif; ?>
				<h1><?= $activity['title'] ?></h1>
				<p><?= $activity['description'] ?></p>
				<?php if ($activity['company_visit'] || session_is_admin ()): ?>
					<div class="corner btn-group" role="group">
						<?php if ($activity['company_visit']): ?>
							<a class="btn btn-primary" href="/companies/index.php?view=read&id=<?= $activity['company_id'] ?>" role="button">Read more</a>
							<a class="btn btn-secondary" href="/companies" role="button">All company visits</a>
						<?php endif; ?>
						<?php if (session_is_admin ()): ?>
							<a class="btn btn-secondary" href="/programme/index.php?view=update&id=<?= $activity['id'] ?>" role="button">Edit</a>
							<a class="btn btn-danger" href="/programme/index.php?view=delete&id=<?= $activity['id'] ?>" role="button">Delete</a>
						<?php endif; ?>
					</div>
				<?php endif; ?>
			</div>
		</div>
	<?php endforeach; ?>

<?php endforeach; ?>

<?php $this->end() ?>
