<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('title') ?>
Programme
<?php $this->end() ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/programme.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('extra_navbar_button') ?>
	<li class="nav-item" >
		<a class="bg-success" href="/programme/index.php?view=create">New Activity</a>
	</li>
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="banner decreased-margin-bottom">
	<div class="third-width">
		<img src="/static/img/programme/destination_banner_01.png">
	</div>
	<div class="third-width">
		<img src="/static/img/programme/destination_banner_02.png">
	</div>
	<div class="third-width">
		<img src="/static/img/programme/destination_banner_03.png">
	</div>
</div>
<div class="banner sticky-top extra-padding-top">
	<a href="#pre-excursion">
		<div class="third-width">
			<img src="/static/img/programme/destination_title_banner_01.png">
		</div>
	</a>
	<a href="#city-01">
		<div class="third-width">
			<img src="/static/img/programme/destination_title_banner_02.png">
		</div>
	</a>
	<a href="#city-02">
		<div class="third-width">
			<img src="/static/img/programme/destination_title_banner_03.png">
		</div>
	</a>
</div>

<?php 
	$activities = [];
	foreach (get_model('Programme')::$sections as $section)
		$activities[$section] = [];
	foreach ($objects as $activity)
		$activities[$activity['section']][] = $activity;
?>

<?php foreach (get_model('Programme')::$sections as $section): ?>
	<?php $set = $activities[$section];
		usort($set, function($a, $b) {
			return strtotime($a['date']) - strtotime($b['date']);
		});
		foreach ($set as $activity): ?>
		<div class="programme-item">
			<div class="programme-item-photo">
				<img src="/static/img/programme/<?= $activity['image_name'] ?>">
			</div>
			<div class="programme-item-text">
				<?php if (!empty($activity['date']) || DEBUG): ?>
					<h4><?= date_format(new DateTime($activity['date']), "jS \of F") . ($activity['show_time'] ? " &middot; " . date_format(new DateTime($activity['time']), "H:i") : "") ?></h4>
				<?php endif; ?>
				<h1><?= $activity['title'] ?></h1>
				<p><?= $activity['description'] ?></p>
				<?php if ($activity['company_visit'] || (cover_session_logged_in() && cover_session_in_committee(ADMIN_COMMITEE)) || DEBUG): ?>
					<div class="corner btn-group" role="group">
						<?php if ($activity['company_visit']): ?>
							<a class="btn btn-primary" href="/companies/index.php?view=read&id=<?= $activity['company_id'] ?>" role="button">Read more</a>
							<a class="btn btn-secondary" href="/companies" role="button">All company visits</a>
						<?php endif; ?>
						<?php if ((cover_session_logged_in() && cover_session_in_committee(ADMIN_COMMITEE)) || DEBUG): ?>
							<a class="btn btn-secondary" href="/programme/index.php?view=update&id=<?= $activity['id'] ?>" role="button">Edit</a>
							<a class="btn btn-danger" href="/programme/index.php?view=delete&id=<?= $activity['id'] ?>" role="button">Delete</a>
						<?php endif; ?>
					</div>
				<?php endif; ?>
			</div>
		</div>
	<?php endforeach; ?>

	<img src="/static/img/programme/end-of-section-banners/<?= $section ?>.png" class="banner" id="<?= $section ?>">

<?php endforeach; ?>

<?php $this->end() ?>
