<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/admin.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
	<h1>Delete activity</h1>
	<form method="POST">
		<fieldset disabled>
			<div class="form-group">
				<label for="id">Activity ID</label>
				<input class="form-control disabled" type="text" name="id" id="id" value="<?= $object['id'] ?>">
			</div>
			<div class="form-group">
				<label for="title">Activity name</label>
				<input class="form-control disabled" type="text" name="title" id="title" value="<?= $object['title'] ?>">
			</div>
		</fieldset>
		<div class="form-group">
			<button class="btn btn-danger" type="submit">Permanently delete this activity</button>
		</div>
	</form>
	
</div>
<?php $this->end() ?>
