<?php $this->extends('../layout.phtml') ?>

<?php $this->begin('title') ?>
Admin &bull; Add Activity
<?php $this->end() ?>

<?php $this->begin('styles') ?>
<link rel="stylesheet" href="/static/css/admin.css" type="text/css">
<?php $this->end() ?>

<?php $this->begin('content') ?>
<div class="container container-narrow">
	<header>
		<h1>Activity</h1>
	</header>
	<?= $form->render() ?>
</div>
<?php $this->end() ?>
